version: '3.5'

x-app-mount:
  &app-mount
    type: bind
    source: ./
    target: /app

services:
    php:
        working_dir: /app
        build:
            context: ./
            dockerfile: Dockerfile-php
        volumes:
            - *app-mount
        environment:
            - XDEBUG_CONFIG="idekey=PHPSTORM remote_enable=On remote_port=9001 profiler_enable_trigger=On profiler_output_dir=/app/docker/data/php/profile"
        depends_on:
            - db

    db:
        image: postgres:latest
        hostname: db
        environment:
            - POSTGRES_DB=ranges
            - POSTGRES_USER=ranges
            - POSTGRES_PASSWORD=ranges

        ports:
            - 5432:5432
    node:
        build:
          context: ./
          dockerfile: Dockerfile-node
        volumes:
            - ./docs:/app/docs
            - ./docs-src:/app/docs-src
        ports:
            - 8080:8080
        tty: true
        network_mode: host
