version: '3.5'

x-app-mount:
  &app-mount
    type: bind
    source: ./
    target: /app

services:
    php:
        working_dir: /app
        build:
            context: ./
        volumes:
            - *app-mount
        environment:
            - XDEBUG_CONFIG="idekey=PHPSTORM remote_enable=On remote_port=9001 profiler_enable_trigger=On profiler_output_dir=/app/docker/data/php/profile"
        depends_on:
            - db

    db:
        image: postgres:latest
        hostname: db
        env_file:
            - database.env
        ports:
            - 5432:5432
